- title: Local Intra-Articular Delivery of Zoledronic Acid as a Disease-Modifying Therapeutic for Post-Traumatic Osteoarthritis
  authors:
    - Michael A. David
  publisher: University of Delaware Dissertation
  date: "2019-01-01"
  link: http://udspace.udel.edu/handle/19716/24751
  type: dissertation
  tags:
    - dissertation
    - post-traumatic osteoarthritis
    - orthopedics
    - translational
