name: Cite process
on:
  workflow_dispatch:     # lets you run it manually
  schedule:
    - cron: "0 7 * * 1"  # runs weekly (optional)

jobs:
  cite:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SCHOLAR_API_KEY: ${{ secrets.GOOGLE_SCHOLAR_API_KEY }}  # <-- this is the fix

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Sanity check env (won't print key)
        run: |
          if [ -z "${GOOGLE_SCHOLAR_API_KEY}" ]; then
            echo "❌ GOOGLE_SCHOLAR_API_KEY is EMPTY"; exit 1;
          else
            echo "✅ GOOGLE_SCHOLAR_API_KEY present (length: ${#GOOGLE_SCHOLAR_API_KEY})";
          fi

      - name: Install dependencies
        run: pip install -r _cite/requirements.txt

      - name: Run cite
        run: python _cite/cite.py

      - name: Commit updated citations
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/citations.yaml
          git commit -m "Update citations [skip ci]" || echo "No changes"
          git pull --rebase origin main || true
          git push
